name: Sync Fork

on:
  schedule:
    # see https://crontab.guru/#0_0_*_*_*
    - cron:  '0 0 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          ref: BangleAppsOrg
          
      - run: |
          git remote add Bangle https://github.com/espruino/BangleApps.git
          git pull Bangle master
          git push origin
      - run: gh workflow run 21382149
        env:
          GH_TOKEN: ${{ github.token }}
