name: Sync Fork

on:
  schedule:
    # see https://crontab.guru/#0_0_*_*_*
    - cron:  '0 0 * * *'
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          ref: BangleAppsOrg
          
      - run: git remote add Bangle https://github.com/espruino/BangleApps.git
